POST http://localhost/create_user HTTP/1.1
content-type: application/json

{
    "name": "Vinicius Pacheco",
    "email": "viniciusp@test.com",
    "description": "It's just a simple test",
    "permission": "admin"
}

###

POST http://localhost/create_user HTTP/1.1
content-type: application/json

{
    "name": "Vinicius Feitosa",
    "email": "viniciusf@test.com",
    "description": "It's just a simple test",
    "permission": "admin"
}

###

POST http://localhost/create_user HTTP/1.1
content-type: application/json

{
    "name": "Vinicius Pacheco",
    "email": "viniciusp@test.com",
    "description": "It's just a simple test",
    "permission": "user"
}

###

GET http://localhost/users/44280190-84b6-11e8-a235-0242ac120005 HTTP/1.1

###

GET http://localhost/users/1/10 HTTP/1.1

###

GET http://localhost/users/admin/permission HTTP/1.1

###

GET http://localhost/users/user/permission HTTP/1.1