POST http://localhost/user HTTP/1.1
content-type: application/json

{
    "name": "Vinicius Pacheco",
    "email": "vinicius@test.com",
    "description": "It's just a simple test"
}

###

GET http://localhost/users/033174ee-7266-11e8-93b6-0242ac160005 HTTP/1.1

###

GET http://localhost/users/1/10 HTTP/1.1